config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :users
  get 'pages/about'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, :presence => true, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user # makes the current_user availible for the view.

  # helper_method :current_order

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #if it is equal to nil then they need to login ----- if true continue on that session
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
      user = User.find_by_email(params[:email])
      # If the user exists AND the password entered is correct.
      if user && user.authenticate(params[:password])
        # Save the user id inside the browser cookie. This is how we keep the user
        # logged in when they navigate around our website.
        session[:user_id] = user.id
        redirect_to current_user, :notice => "Logged in successfully."
      else
        flash[:login_errors] = ['Invalid credentials, please try again.']
        # redirect_to users_index_path
        redirect_to root_path
      end
    end

    def destroy
      session[:user_id] = nil
      cookies.delete(:auth_token)
      redirect_to root_url, :notice => "Logged out successfully."
    end

    private

    def login_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to current_user

        flash[:register_success] = ["Welcome #{current_user.email}, thank you for registering."]
      else
        flash[:register_errors] = ["REGISTER ERROR. Invalid credentials, please try again."]
        # redirect_to users_index_path
        redirect_to root_path
      end
  end

  def update
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to @user, :notice => "Profile updated successfully."
      else
         redirect_to @user, :alert => "Profile could not be updated, please try again later."
      end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => 'You have successfully deleted your account.'
   else
     redirect_to users_edit_path, :notice => "User can not be deleted at this time."
   end
  end

  private

    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit( :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"> Login Template </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if current_user %>

        <li class="nav-item">
          <%= link_to "Welcome #{current_user.email}",  user_path(current_user), class:"nav-link"   %>
        </li>

        <li class="nav-item">
          <%= link_to 'Account Settings(Users#Edit)',  edit_user_path(current_user), class:"nav-link" %>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/logout"> Logout </a>
        </li>

      <% else %>

        <li class="nav-item">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <%= link_to 'Login', '/login', class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Signup', '/signup', class:"nav-link" %>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/pages/about">About</a>
        </li>

      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Login Template </title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </head>

  <%= render "layouts/nav" %>

  <% if notice != nil %>
    <h4 class="text-center alert-success">
    <br>
    <%= notice %>
    <br>
    <br>
  </h4>
  <% elsif alert != nil %>
    <h4 class="text-center alert-danger">
      <br>
      <%= alert %>
      <br>
      <br>
    </h4>
  <% end %>

  <body>

    <div class="container py-5 text-center">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<br>

A very simple auth application with proper redirects and minimal styling. If you are new to development or even just Ruby on Rails I do <strong>not</strong> reccomend starting to build your app with this templete. I highly suggest learning session management before using anyone elses auth.

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <br>
    <%= form.text_field :email, id: :user_email%>
  </div>
<br>

  <div class="field">
    <%= form.label :password %>
    <br>
    <%= form.password_field :password, id: :user_password %>
  </div>
<br>

  <div class="field">
    <%= form.label :password, "Password Confirmation" %>
    <br>
    <%= form.password_field :password_confirmation, id: :user_password %>
  </div>
<br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>

  <td><%= link_to 'Deactivate Account', {:controller=>:users,:action=>:destroy, :id=>@user}, :method=>:delete, data: { confirm: 'Are you sure you would like to deactivate your account forever? Once deactivated it can never be recovered.' }, class:"btn btn-sm btn-danger", :style => "color: #f8f8f8;" %></td>

  <hr>
  <br>

app/views/users/edit.html.erb
<div class="card py-5 text-center">
<div class="container">


<h1 class="text-center">Account Settings</h1>
<hr>
<%= render 'form', user: @user %>

<div>
  <%= link_to 'Back', :back, class:"btn btn-outline-primary" %>
</div>


</div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="card">
  <br>

  <h1 class="text-center">Signup</h1>

  <div class="container">
    <hr>
  </div>

<br>

  <%= form_for :user, url: '/users' do |f| %>

      <div class="form-group">
      <strong>Email:</strong>  <%= f.text_field :email, placeholder: "Enter your Email" %>
      </div>

      <div class="form-group">
        <strong>Password:</strong><%= f.password_field :password, placeholder: "Password" %>
      </div>

      <div class="form-group">
            <strong>Confirm Password:</strong>  <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
      </div>

      <br>
       <center class="submit">
        <%= f.submit "Submit", class:"btn btn-success" %>
      </center>
      <br>

      <small>
        Already have an account? <%= link_to "Click Here to Login.", login_path %>
      </small>

      <br>
  <% end %>

<br>

</div>

app/views/users/show.html.erb
<h1>Users#Show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<br>
<br>
<br>

<h1>  Welcome <%= current_user.email %> </h1>